config/routes.rb
Rails.application.routes.draw do

  resources :theme_colors

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :localizables
      resources :jenkins
    end
  end

  get 'jenkins' => 'jenkins#index'

  resources :localizables

  get 'admin' => 'menu#home'
  get 'start_jenkins' => 'menu#start_jenkins'
  get 'trigger_build' => 'menu#trigger_build'

  controller :sessions do
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => 'menu#home'
    get 'login' => 'menu#home'
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users do
    member do
      get 'edit2' => :edit2
    end
  end

  resources :at_strings

  resources :numbers

  resources :couleurs

  resources :apps

  root 'menu#home'

end

app/controllers/menu_controller.rb
require 'net/http'


class MenuController < ApplicationController
  skip_before_action :authorize

  def home
  end

  def trigger_build
    puts params.to_s

    app = params[:name]
    app= app.gsub(/([ ])/,"%20")
    uri = URI("http://server.mobservic.es:8080/jenkins/view/#{app}/job/#{app}/build")
    req = Net::HTTP::Post.new(uri)
    req.basic_auth 'bitbucket', 'wasapplibitbucket'

    res = Net::HTTP.start(uri.hostname, uri.port) do |http|
      http.request(req)
    end

    case res
      when Net::HTTPSuccess, Net::HTTPRedirection
        trigger = true
      # OK
      else
        trigger = false
        res.value
    end

    if (trigger == true)
      flash[:success] = "Build triggered"
    else
      flash[:error] = "Something went wrong when triggering"
    end
    redirect_to start_jenkins_path(:name => params[:name])

  end
end

app/helpers/menu_helper.rb
module MenuHelper



end

app/views/menu/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
<% end %>

app/views/menu/_home_logged.html.erb
<% user = User.find(session[:user_id]); %>
<% user.name %>
<section id="main-content">
  <section class="wrapper">
    <br/>
    <br/>
    <section class="panel">
      <header class="panel-heading">
        <h2>Select an App</h2>
      </header>
      <div class="panel-body">
        <div class="adv-table">
          <div id="example_wrapper" class="dataTables_wrapper form-inline" role="grid">

            <table class="display table table-bordered dataTable" id="example" aria-describedby="example_info">
              <thead>
              <tr role="row">
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="App Name: activate to sort column ascending" style="width: 360px;">
                  App Name
                </th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Colors: activate to sort column ascending" style="width: 360px;">Colors</th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Numbers: activate to sort column ascending" style="width: 360px;">Numbers</th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Strings: activate to sort column ascending" style="width: 360px;">Strings</th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending" style="width: 360px;">Localizable</th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending" style="width: 360px;">Theme</th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending" style="width: 360px;">Action</th>
              </tr>
              </thead>

              <tfoot>
              <tr>
                <th rowspan="1" colspan="1">App Name</th>
                <th rowspan="1" colspan="1">Colors</th>
                <th rowspan="1" colspan="1">Numbers</th>
                <th rowspan="1" colspan="1">Strings</th>
                <th rowspan="1" colspan="1">Localizable</th>
                <th rowspan="1" colspan="1">Theme</th>
                <th rowspan="1" colspan="1">Action</th>
              </tr>
              </tfoot>
              <tbody role="alert" aria-live="polite" aria-relevant="all">
              <% user.apps.each do |app| %>
                  <tr>
                    <td><%= app.name %></td>
                    <td><%= link_to 'Modify Colors', couleurs_path(:app_id => app.id), :class => "btn btn-sm btn-round btn-success" %></td>
                    <td><%= link_to 'Modify Numbers', numbers_path(:app_id => app.id), :class => "btn btn-sm btn-round btn-danger" %></td>
                    <td><%= link_to 'Modify Strings', at_strings_path(:app_id => app.id), :class => "btn btn-sm btn-round btn-primary" %></td>
                    <td><%= link_to 'Modify Localizable', localizables_path(:app_id => app.id), :class => "btn btn-sm btn-round btn-info" %></td>
                    <td><%= link_to 'Modify Color Theme', theme_colors_path(:app_id => app.id), :class => "btn btn-sm btn-round" %></td>
                    <td><%= link_to 'Launch Jenkins', start_jenkins_path(:name => app.name), :class => "btn btn-sm btn-round btn-warning" %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  </section>
</section>

app/views/menu/home.html.erb
<%= render partial: "flash_messages", flash: flash %>

<% if (session[:user_id]!= nil) %>
    <%= render :partial => "menu/home_logged" %>
<% end %>

<% if (session[:user_id]== nil) %>
    <div class="container">
      <%= render :partial => "sessions/new" %>
    </div>
<% end %>

app/views/menu/start_jenkins.html.erb
<br>
<br>
<section class="wrapper" id="main-content" style="width: 85%">

  <%= render partial: "flash_messages", flash: flash %>

  <%= link_to 'Go Back', root_path, :class => "btn btn-big btn-primary" %>
  <%= link_to 'Trigger Build/ Deploy', trigger_build_path(:name => params[:name]), :class => "btn btn-big btn-primary" %>
  <br>
  <br>

  <section class="panel">
    <header class="panel-heading tab-bg-dark-navy-blue ">
      <ul class="nav nav-tabs">
        <li class="active">
          <a data-toggle="tab" href="#Constants">Constants.h</a>
        </li>
        <% @langs = LocalizablesHelper.get_all_langs params[:name]
           @langs.each do |lang| %>
            <li class="">
              <%= link_to "#{lang}", "##{lang}", :data => {:toggle => "tab"} %>
            </li>
        <% end %>
      </ul>
    </header>
    <div class="panel-body">
      <div class="tab-content">
        <div id="Constants" class="tab-pane active">
          <pre style="font-size: 11px">
            <% lines_final = ApplicationHelper.getStrings(params[:name]) %>
            <% if lines_final!= nil %>
                <% lines_final.each do |line| %>
                <%= line.to_s %>
                <% end %>
            <% else %>
                <%= "Pas de fichier Constants.h pour ce projet" %>
            <% end %>
          </pre>
        </div>
        <% @langs.each do |lang| %>
            <div id="<%= lang %>" class="tab-pane">
               <pre style="font-size: 11px">
                 <% @lines_tab= Hash.new
                    @lines_tab = LocalizablesHelper.writeLocs(params[:name]) %>
                 <% if @lines_tab["#{lang}"] == nil %>
                    <%= "Pas de fichier Localization.string dans le repertoire" %>
                 <% else
                      @lines_tab["#{lang}"].each do |array|
                        if array.instance_of?(Array) %>
                            <%= "\"#{array[0]}\" = \"#{array[1]}\"" %>
                        <% else %>
                            <%= array.to_s %>
                        <% end %>
                    <% end %>
                 <% end %>
                </pre>
            </div>
        <% end %>
      </div>
    </div>
  </section>


</section>

app/views/menu/start_jenkins_text.text.erb
<% lines_final = ApplicationHelper.getStrings(params[:format]) %>
<% lines_final.each do |line| %>
    <%= line.to_s %>
<% end %>