config/routes.rb
Rails.application.routes.draw do

  resources :theme_colors

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :localizables
      resources :jenkins
    end
  end

  get 'jenkins' => 'jenkins#index'

  resources :localizables

  get 'admin' => 'menu#home'
  get 'start_jenkins' => 'menu#start_jenkins'
  get 'trigger_build' => 'menu#trigger_build'

  controller :sessions do
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => 'menu#home'
    get 'login' => 'menu#home'
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users do
    member do
      get 'edit2' => :edit2
    end
  end

  resources :at_strings

  resources :numbers

  resources :couleurs

  resources :apps

  root 'menu#home'

end

app/models/localizable.rb
class Localizable < ActiveRecord::Base
  belongs_to :app
end

app/controllers/api/v1/localizables_controller.rb
module Api
  module V1
    class LocalizablesController < ApplicationController
      skip_before_action :authorize
      skip_before_action :verify_authenticity_token
      respond_to :json

      def index
        app = App.where("name = '#{params[:name]}'")
        loc = Localizable.where("app_id = #{app[0].id}")
        respond_with loc
      end

      def show
        respond_with Localizable.find(params[:app_id])
      end

      def create
        #compute the token into app_id
        app = App.where(:app_token => params[:app_token])
        if (app.size!=0)
          params[:localizable].merge(:app_id => app[0].id)
          loc = Localizable.new(params[:localizable].permit(:key_loc, :value, :lang, :app_token, :missing))
          loc.app = app[0]
          loc.save
          respond_with loc
        end
      end

      def update
        respond_with Localizable.update(params[:app_id], params[:localizables])
      end

      def destroy
        respond_with Localizable.destroy(params[:app_id])
      end
    end
  end
end

app/controllers/localizables_controller.rb
class LocalizablesController < ApplicationController
  before_action :set_localizable, only: [:show, :edit, :update, :destroy]

  # GET /localizables
  # GET /localizables.json
  def index
    @user=User.find(session[:user_id])
    if (params.has_key?("app_id"))
      @app = @user.apps.find(params[:app_id])
      LocalizablesHelper.getLang params[:app_id]
    end
  end

  # GET /localizables/1
  # GET /localizables/1.json
  def show
  end

  # GET /localizables/new
  def new
    @localizable = Localizable.new
  end

  # GET /localizables/1/edit
  def edit
  end

  # POST /localizables
  # POST /localizables.json
  def create
    @localizable = Localizable.new(localizable_params)
    @localizable.app_id = params[:localizable][:app_id]

    #by default missing has to be true, then it changes when rendering the table
    @localizable.missing = true
    
    respond_to do |format|
      if @localizable.save
        format.html { redirect_to localizables_path(:app_id => @localizable.app_id), notice: 'Localizable was successfully created.' }
        format.json { render :show, status: :created, location: @localizable }
      else
        format.html { render :new }
        format.json { render json: @localizable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localizables/1
  # PATCH/PUT /localizables/1.json
  def update
    session[:app_id]=params[:localizable][:app_id]

    #by default missing has to be true, then it changes when rendering the table
    @localizable.missing = true

    respond_to do |format|
      if @localizable.update(localizable_params)
        format.html { redirect_to localizables_path(:app_id => @localizable.app_id), notice: 'Localizable was successfully updated.' }
        format.json { render :show, status: :ok, location: @localizable }
      else
        format.html { render :edit }
        format.json { render json: @localizables.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localizables/1
  # DELETE /localizables/1.json
  def destroy
    app_id = @localizable.app_id
    @localizable.destroy
    respond_to do |format|
      format.html { redirect_to localizables_path(:app_id => app_id) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_localizable
    @localizable = Localizable.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def localizable_params
    params.require(:localizable).permit(:key_loc, :value, :lang, :app_id, :missing)
  end

end

app/helpers/localizables_helper.rb
require 'find'
require_relative 'pre_build'

module LocalizablesHelper

  def getLang id
    @app_id = id
    app_name = App.find(id).name
    @path ="/Users/wasappliserver/.jenkins/jobs/#{app_name}/workspace/#{app_name}"
    @lang_tab = Array.new

    @lines_tab = Hash.new

    if (File.exist?(@path))
      Find.find(@path) do |path|
        if (path =~ /.*\.lproj$/)
          @lang_tab << path
        end
      end
    end

    puts "TABLEAU DES LANGUES "+ @lang_tab.to_s

    #for each lang
    for i in 0..@lang_tab.length-1
      el = @lang_tab[i][/(\w+).lproj$/]
      el2 = el[/^(\w+)/]
      lang = el2
      puts "LANG IS ===>" + lang.to_s
      # first we add the lang in th DB
      addLangs lang
      @lines_tab["#{lang}"] = Array.new

      #get the list of the variables in the file
      @lines_tab["#{lang}"] = getLocalizables lang
      #puts "LANNNNG " + @lines_tab["#{lang}"].to_s
      if (@lines_tab["#{lang}"] == "No File Found")
        puts "skipped no localizable.strings found"
        @lines_tab["#{lang}"]= nil
      else
        @lines_tab["#{lang}"].each do |line|
          #if we already have the row in the DB
          puts line[0]
          query = Localizable.where("app_id = '#{@app_id}' and key_loc = '#{line[0]}' and lang = '#{lang}'")
          if query.count != 0
            #puts 'this entry is already in the database'
          else
            Localizable.create!(key_loc: line[0], value: line[1], lang: lang, app_id: @app_id)
          end
        end

      end
    end
  end

  module_function :getLang

  def addLangs lang

    # get the list of the localize
    lines_tab = getLocalizables lang
    #puts "liens " + lines_tab.to_s

    if (lines_tab == "No File Found" || lines_tab == 0)
      puts "skipped no localizable.strings found"
    else
      lines_tab.each do |line|
        query = Localizable.where(:key_loc => line[0], :app_id => @app_id, :lang => lang)
        if query.count != 0
          #puts 'this entry is already in the database'
          break
        else
          Localizable.create!(:key_loc => line[0], :value => line[1], :app_id => @app_id, :lang => lang)
        end
      end
    end
  end

  module_function :addLangs

  def getLocalizables lang
    line_tab = Array.new

    path_loc = "#{@path}/#{lang}.lproj/Localizable.strings"
    #If the file exist
    if (File.exist?(path_loc))
      #open it
      File.open(path_loc, 'r+') do |file|
        #read files, stores it in an table
        @lines = file.read

        lines_tab = @lines.scan(/\s*\"(.*)\"\s*=\s*\"([\S\s]*?)\"\s*;/)
        #puts lines_tab
        return lines_tab
      end
    else
      puts "NO FILE FOUND FOR LANG #{lang} AT #{path_loc}"
      return "No File Found"
    end
  end

  module_function :getLocalizables

  def writeLocs app_name

    #gets all the values from the DB for localization, stores them in array
    app = App.find_by name: app_name

    @path ="/Users/wasappliserver/.jenkins/jobs/#{app_name}/workspace/#{app_name}"
    @lang_tab = Array.new

    @lines_tab = Hash.new

    if (File.exist?(@path))
      Find.find(@path) do |path|
        if (path =~ /.*\.lproj$/)
          @lang_tab << path
        end
      end
    end

    for i in 0..@lang_tab.length-1
      el = @lang_tab[i][/(\w+).lproj$/]
      el2 = el[/^(\w+)/]
      lang = el2
      puts "LANG IS ===>" + lang.to_s
      @lines_tab["#{lang}"] = Array.new

      #get the list of the variables in the file
      @lines_tab["#{lang}"] = getLocalizables lang
      puts "LANNNNG " + @lines_tab["#{lang}"].to_s
      if (@lines_tab["#{lang}"] == "No File Found")
        puts "skipped no localizable.strings found"
        @lines_tab["#{lang}"]= nil
      else
        #update the DB
        @row_localizable = Localizable.where("app_id = '#{app.id}' and lang = '#{lang}'")
        @row_localizable.each do |row|

          if (compareLinesL(row, lang) == false)
            addRowLocalizable row, lang
          end
        end

      end
    end

    return @lines_tab

  end

  module_function :writeLocs

  def get_all_langs app_name
    path ="/Users/wasappliserver/.jenkins/jobs/#{app_name}/workspace/#{app_name}"
    lang_tab = Array.new

    if (File.exist?(path))
      Find.find(path) do |p|
        if (p =~ /.*\.lproj$/)
          el = p[/(\w+).lproj$/]
          el2 =el[/^(\w+)/]
          lang_tab << el2
        end
      end
    end

    return lang_tab
  end

  module_function :get_all_langs

  def findNotMissing localizable

    puts "for #{localizable.lang}BOOLEAN +> " + localizable.missing.to_s
    #search if another row in the DB has the same key_loc
    loc_row = Localizable.where("key_loc = '#{localizable.key_loc}'")
    #if yes, we check if there are as many lang as key_loc,
    count_rows = loc_row.length
    puts "nombres de rows #{count_rows}"

    if (count_rows > 0)
      app = App.find(localizable.app_id)
      lang_tab = get_all_langs app.name

      puts "nombres de langues #{lang_tab.size}"

      # if yes that means value is translated into all languages
      if (lang_tab.length == count_rows)
        localizable.missing = false
        puts "BOOLEAN IS NOW"+localizable.missing.to_s
        localizable.save
      end
    end

  end

  module_function :findNotMissing
end

app/views/localizables/_form.html.erb
<div class="panel-body">
  <%= form_for @localizable, :html => {:class => 'form-horizontal'} do |f| %>
      <% if @localizable.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@localizable.errors.count, "error") %> prohibited this number from being saved:</h2>

            <ul>
              <% @localizable.errors.full_messages.each do |message| %>
                  <li>
                    <%= message %>
                  </li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="form-group">
        <%= f.label :key_loc, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :key_loc, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :value, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :value, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :lang, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :lang, :class => 'form-control' %>
        </div>
      </div>



      <% if (params[:app_id]!=nil)
           app_id= params[:app_id]
         else
           app_id = @localizable.app_id
         end %>
      <%= f.hidden_field :app_id, :value => "#{app_id}" %>
      <div class="form-actions">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    localizables_path(:app_id => app_id), :class => 'btn' %>
      </div>
  <% end %>
</div>

app/views/localizables/edit.html.erb
<section id="main-content">
  <section class="wrapper">
    <br/>
    <br/>

    <div class="form-size">
      <section class="panel">
        <header class="panel-heading">
          <h1>Edit Localizable</h1>
        </header>
        <%= render :partial => 'form' %>
      </section>
    </div>
  </section>
</section>

app/views/localizables/index.html.erb
<%- model_class = Localizable -%>
<% %>
<section class="wrapper" id="main-content">
  <br>
  <br>
  <section class="panel">
    <header class="panel-heading">

      <h2><%= t '.title', :default => model_class.model_name.human.pluralize.titleize, :class => "text-center" %> de
        l'application <%= @app.name %> </h2>
    </header>
    <div class="panel-body">
      <div class="adv-table">
        <div id="example_wrapper" class="dataTables_wrapper form-inline" role="grid">

          <table class="display table table-condensed table-bordered dataTable" id="example" aria-describedby="example_info">
            <thead>
            <tr role="row">
              <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="0" colspan="0" aria-label="Colors: activate to sort column ascending" style="width: 360px;">Key</th>
              <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="0" colspan="0" aria-label="Numbers: activate to sort column ascending" style="width: 360px;">Value</th>
              <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="0" colspan="0" aria-label="Strings: activate to sort column ascending" style="width: 360px;">Lang</th>
              <th class="sorting" role="columnheader" tabindex="0" aria-controls="example" rowspan="0" colspan="0" aria-label="Action: activate to sort column ascending" style="width: 360px;"><%= t '.actions', :default => t("helpers.actions") %></th>
            </tr>
            </thead>
            <tfoot>
            <tr>
              <th rowspan="0" colspan="0">Key</th>
              <th rowspan="0" colspan="0">Value</th>
              <th rowspan="0" colspan="0">Lang</th>
              <th rowspan="0" colspan="0">Action</th>
            </tr>
            </tfoot>
            <tbody role="alert" aria-live="polite" aria-relevant="all">
            <% @app.localizables.each do |localizable| %>
                <% if localizable.missing == true
                     LocalizablesHelper.findNotMissing localizable
                   end %>
            <% end %>
            <% @app.localizables.each do |localizable| %>
                <% if localizable.missing == true
                     missing = "missing"
                   else
                     missing=""
                   end %>

                <tr class="<%= "#{missing}" %>">
                  <td><%= localizable.key_loc %></td>
                  <td><%= localizable.value %></td>
                  <td><%= localizable.lang %></td>
                  <td> <%= link_to t('.edit', :default => t("helpers.links.edit")),
                                   edit_localizable_path(localizable), :class => 'btn btn-mini' %>
                    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                localizable_path(localizable),
                                :method => :delete,
                                :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                                :class => 'btn btn-xs btn-danger' %> </td>
                </tr>
            <% end %>
            </tbody>
          </table>


        </div>
      </div>
    </div>

  </section>
  <%= link_to 'New Localizable Value', new_localizable_path(:app_id => @app.id), :class => 'btn btn-info' %>
  <%= link_to "Back to menu", root_path, :class => 'btn btn-secondary' %>
</section>

app/views/localizables/new.html.erb
<section id="main-content">
  <section class="wrapper">
    <br/>
    <br/>

    <div class="form-size">
      <section class="panel">
        <header class="panel-heading">
          <h1>New Localizable</h1>
        </header>
        <%= render :partial => 'form' %>
      </section>
    </div>
  </section>
</section>

app/views/localizables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @localizable.key_loc %>
</p>

<p>
  <strong>Value:</strong>
  <%= @localizable.value %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @localizable.lang %>
</p>

<p>
  <strong>App:</strong>
  <%= @localizable.app_id %>
</p>

<p>
  <strong>Missing:</strong>
  <%= @localizable.missing %>
</p>

<%= link_to 'Edit', edit_localizable_path(@localizable) %> |
<%= link_to 'Back', localizables_path %>