config/routes.rb
Rails.application.routes.draw do

  resources :theme_colors

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :localizables
      resources :jenkins
    end
  end

  get 'jenkins' => 'jenkins#index'

  resources :localizables

  get 'admin' => 'menu#home'
  get 'start_jenkins' => 'menu#start_jenkins'
  get 'trigger_build' => 'menu#trigger_build'

  controller :sessions do
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => 'menu#home'
    get 'login' => 'menu#home'
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users do
    member do
      get 'edit2' => :edit2
    end
  end

  resources :at_strings

  resources :numbers

  resources :couleurs

  resources :apps

  root 'menu#home'

end

app/views/apps/_form.html.erb
<%= form_for @app, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :app_token, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :app_token, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  apps_path, :class => 'btn' %>
    </div>
<% end %>

app/views/apps/edit.html.erb
<section class="wrapper" id="main-content">
  <%- model_class = App -%>
  <div class="page-header">
    <h1><%= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>
</section>

app/views/apps/index.html.erb
<section class="wrapper" id="main-content">
  <%- model_class = App -%>

  <div class="page-header">
    <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <table class="table table-striped wrapper">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:token) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @apps.each do |app| %>
        <tr>
          <td><%= link_to app.id, app_path(app) %></td>
          <td><%= app.name %></td>
          <td><%= app.app_token %></td>
          <td><%= l app.created_at %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_app_path(app), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        app_path(app),
                        :method => :delete,
                        :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_app_path,
              :class => 'btn btn-primary' %>
  <%= link_to "Back to menu", root_path, :class => 'btn btn-secondary' %>
</section>

app/views/apps/new.html.erb
<section class="wrapper" id="main-content">
  <%- model_class = App -%>
  <div class="page-header">
    <h1><%= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>
</section>

app/views/apps/show.html.erb
<section class="wrapper">
<%- model_class = App -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @app.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              apps_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_app_path(@app), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              app_path(@app),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
</section>