config/routes.rb
Rails.application.routes.draw do

  resources :theme_colors

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :localizables
      resources :jenkins
    end
  end

  get 'jenkins' => 'jenkins#index'

  resources :localizables

  get 'admin' => 'menu#home'
  get 'start_jenkins' => 'menu#start_jenkins'
  get 'trigger_build' => 'menu#trigger_build'

  controller :sessions do
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => 'menu#home'
    get 'login' => 'menu#home'
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users do
    member do
      get 'edit2' => :edit2
    end
  end

  resources :at_strings

  resources :numbers

  resources :couleurs

  resources :apps

  root 'menu#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacePickers</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<section id="container">
  <% if (session[:user_id]!= nil) %>
      <% user = User.find(session[:user_id]); %>
      <header class="header white-bg">

        <div class="top-nav ">
          <ul class="nav pull-right top-menu">
            <!-- user login dropdown start-->
            <li class="dropdown" style="padding-top: 8%">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <img alt="" src="assets/img/avatar1_small.jpg">
                <span class="username"><%= user.name %></span> <b class="caret"></b> </a>
              <ul class="dropdown-menu extended logout">
                <div class="log-arrow-up"></div>
                <li>
                  <%= link_to 'Apps <i class="fa fa-gamepad"></i>'.html_safe, apps_path, :class => 'btn' %>
                </li>
                <li>
                  <%= link_to 'Users <i class="fa fa-users"></i>'.html_safe, users_path, :class => "btn" %>

                </li>
                <li>
                  <%= link_to 'Logout <i class="fa fa-key"></i>'.html_safe, logout_path, method: :delete, :class => "btn" %>
                </li>
              </ul>
            </li>
            <!-- user login dropdown end -->
          </ul>
        </div>

        <%= link_to "HOME", root_path, :class => 'logo' %>
        <h1 class="text-center">Wasappli Constant Picker</h1>

      </header>
  <% end %>

  <% if (session[:user_id]!= nil) %>
      <aside>
        <div id="sidebar" class="nav-collapse " tabindex="5000" style="overflow: hidden; outline: none;">

          <!-- sidebar menu start-->
          <ul class="sidebar-menu" id="nav-accordion">

            <!--multi level menu start-->
            <li class="sub-menu dcjq-parent-li">
              <a href="javascript:;" class="dcjq-parent"> <i class="fa fa-sitemap"></i> <span>Application List:</span>
                <span class="dcjq-icon"></span></a>
              <ul class="sub" style="display: none;">
                <!--Sub Menu start-->
                <% user = User.find(session[:user_id]); %>
                <% user.apps.each do |app| %>
                    <li class="sub-menu dcjq-parent-li">
                      <a href="boxed_page.html" class="dcjq-parent"><%= app.name %><span class="dcjq-icon"></span></a>
                      <ul class="sub" style="display: none;">
                        <li>
                          <%= link_to 'Modify Colors', couleurs_path(:app_id => app.id) %>
                        </li>
                        <li>
                          <%= link_to 'Color Theme', theme_colors_path(:app_id => app.id) %>
                        </li>
                        <li>
                          <%= link_to 'Modify Numbers', numbers_path(:app_id => app.id) %>
                        </li>

                        <li>
                          <%= link_to 'Modify Strings', at_strings_path(:app_id => app.id) %>
                        </li>

                        <li>
                          <%= link_to 'Modify Localizables', localizables_path(:app_id => app.id) %>
                        </li>

                        <li>
                          <%= link_to 'Launch Jenkins', start_jenkins_path(:name => app.name) %>
                        </li>

                      </ul>
                    </li>
                <% end %>
              </ul>
            </li>

            <!--multi level menu end-->
          </ul>

          <!-- sidebar menu end-->
        </div>

      </aside>
  <% end %>
  <%= yield %>
</section>

</body>
</html>